apiVersion: v1
kind: ConfigMap
metadata:
  name: google-sdp-evaluation
  namespace: google-sdp-evaluation
data:
  region: us-east1
  endpoint: dlp.us-east1.rep.googleapis.com
  synthetic_corpus_path: /app/evaluation/google-sdp/corpus.json
