apiVersion: v1
kind: LimitRange
metadata:
  name: google-sdp-evaluation
  namespace: google-sdp-evaluation
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 64Mi
      default:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 256Mi
      max:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 256Mi
