apiVersion: v1
kind: ServiceAccount
metadata:
  name: google-sdp-evaluation
  namespace: google-sdp-evaluation
  annotations:
    iam.gke.io/gcp-service-account: REPLACE_WITH_GSA_EMAIL
automountServiceAccountToken: true
