apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
  labels:
    app.kubernetes.io/name: ai-platform
    app.kubernetes.io/part-of: ai-platform
    app.kubernetes.io/managed-by: kustomize
    environment: demo
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.35
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.35
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.35
