"""Idempotent platform bootstrap job (`python -m agent_platform.programs.bootstrap all`).

database: non-owner login roles (NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS), databases, the
          LiteLLM schema, the RLS tenant schema (FORCE ROW LEVEL SECURITY) and synthetic fixtures.
keys:     scoped gateway virtual keys (pre-generated by `make secrets`) with model = the stable alias only and a
          30-day budget; the sum of all key budgets is the owner-approved $10/month.
Re-running changes nothing that already exists. Never prints secret values.
"""
import json
from pathlib import Path
import sys
import time
import urllib.error
import urllib.request

TENANTS = {'fixture-a': '7d5bba9e-0f6f-4f3e-9b6c-2b8f2f0a1a01', 'fixture-b': 'c4a1f3de-5b2e-4d8f-8a7c-91e0b6d2c302'}
SQL = Path('/sql')
GATEWAY = 'http://gateway.platform.svc.cluster.local:4000'


def log(**fields):
    print(json.dumps({'audit_event': 'bootstrap', 'component': 'bootstrap', **fields}, sort_keys=True), flush=True)


def url(config, role, database):
    password = {'postgres': config['owner_password'], 'portfolio_gateway': config['gateway_password']}[role]
    return 'postgresql://' + role + ':' + password + '@' + config['host'] + '/' + database


def database(config):
    import psycopg
    from psycopg import sql
    with psycopg.connect(url(config, 'postgres', 'postgres'), connect_timeout=5, autocommit=True) as db:
        for role, password in (('portfolio_gateway', config['gateway_password']), ('portfolio_app', config['app_password'])):
            exists = db.execute('SELECT 1 FROM pg_roles WHERE rolname=%s', (role,)).fetchone()
            verb = 'ALTER' if exists else 'CREATE'
            db.execute(sql.SQL(verb + ' ROLE {} LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD {}')
                       .format(sql.Identifier(role), sql.Literal(password)))
        for name, owner in (('litellm', 'portfolio_gateway'), ('portfolio_demo', None)):
            if not db.execute('SELECT 1 FROM pg_database WHERE datname=%s', (name,)).fetchone():
                db.execute(sql.SQL('CREATE DATABASE {}' + (' OWNER {}' if owner else '')).format(
                    sql.Identifier(name), *([sql.Identifier(owner)] if owner else [])))
            db.execute(sql.SQL('REVOKE CONNECT ON DATABASE {} FROM PUBLIC').format(sql.Identifier(name)))
        db.execute('GRANT CONNECT ON DATABASE litellm TO portfolio_gateway')
        db.execute('GRANT CONNECT ON DATABASE portfolio_demo TO portfolio_app')
    with psycopg.connect(url(config, 'portfolio_gateway', 'litellm'), connect_timeout=5, autocommit=True) as db:
        if not db.execute("SELECT to_regclass('public.\"LiteLLM_VerificationToken\"')").fetchone()[0]:
            db.execute((SQL / 'litellm-schema.sql').read_text())
            log(step='litellm_schema', created=True)
    with psycopg.connect(url(config, 'postgres', 'portfolio_demo'), connect_timeout=5, autocommit=True) as db:
        if not db.execute("SELECT to_regclass('portfolio_demo.expenses')").fetchone()[0]:
            db.execute((SQL / 'tenant.sql').read_text())
            fixtures = json.loads((SQL / 'expenses.json').read_text())
            for tenant, rows in fixtures['tenants'].items():
                for row in rows:
                    db.execute('INSERT INTO portfolio_demo.expenses(tenant_id,period,category,amount_minor_units) VALUES(%s,%s,%s,%s)',
                               (TENANTS[tenant], row['period'], row['category'], row['amount_minor_units']))
            log(step='tenant_schema', created=True)
        rls = db.execute("SELECT relrowsecurity, relforcerowsecurity FROM pg_class WHERE oid='portfolio_demo.expenses'::regclass").fetchone()
        bypass = db.execute("SELECT rolbypassrls, rolsuper FROM pg_roles WHERE rolname='portfolio_app'").fetchone()
        if rls != (True, True) or bypass != (False, False):
            raise SystemExit('bootstrap:rls_contract_violated')
    log(step='database', rls_forced=True, app_role_bypassrls=False)


def _gateway(path, body, master_key, method='POST'):
    request = urllib.request.Request(GATEWAY + path, method=method, data=None if body is None else json.dumps(body).encode(),
                                     headers={'Authorization': 'Bearer ' + master_key, 'Content-Type': 'application/json'})
    with urllib.request.build_opener(urllib.request.ProxyHandler({})).open(request, timeout=10) as response:
        return json.loads(response.read(1 << 20))


def keys(config, wait_seconds=300):
    deadline = time.time() + wait_seconds
    while True:
        try:
            with urllib.request.build_opener(urllib.request.ProxyHandler({})).open(GATEWAY + '/health/liveliness', timeout=5):
                break
        except Exception:
            if time.time() >= deadline:
                raise SystemExit('bootstrap:gateway_not_ready')
            time.sleep(5)
    if round(sum(k['max_budget'] for k in config['virtual_keys']), 2) != 10.0:
        raise SystemExit('bootstrap:budget_total_must_be_10')
    for item in config['virtual_keys']:
        try:
            _gateway('/key/info?key=' + item['key'], None, config['master_key'], method='GET')
            log(step='virtual_key', alias=item['alias'], created=False)
            continue
        except urllib.error.HTTPError as error:
            if error.code not in (400, 404):
                raise
        _gateway('/key/generate', {'key': item['key'], 'key_alias': item['alias'], 'models': ['secure-financial-chat'],
                                   'max_budget': item['max_budget'], 'budget_duration': '30d',
                                   'rpm_limit': 20, 'max_parallel_requests': 2}, config['master_key'])
        log(step='virtual_key', alias=item['alias'], created=True, max_budget=item['max_budget'])


def main(argv):
    if argv not in (['database'], ['keys'], ['all']):
        raise SystemExit('usage: bootstrap database|keys|all')
    config = json.loads(Path('/secrets/bootstrap/bootstrap.json').read_text())
    if argv[0] in ('database', 'all'):
        database(config)
    if argv[0] in ('keys', 'all'):
        keys(config)


if __name__ == '__main__':
    main(sys.argv[1:])
